import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="m-10 mx-auto max-w-sm flex-row items-center rounded-xl bg-white p-6 shadow-lg outline outline-black/5">
      <div className="text-xl text-center">
        <p>Awesome Loggily Dashboard</p>
      </div>
      <div className="text-gray-500 text-center">
        <p>Coming Soon...</p>
      </div>
    </div>
  );
}
